steps:
    - name: 'node:${_NODE_VERSION}'
      entrypoint: 'npm'
      args: ['ci']
      id: ci
    #  - name: 'gcr.io/cloud-builders/gcloud'
    #    args:
    #      - app
    #      - deploy
    #      - [FUNCTION_NAME]
    #      - --source=.
    #      - --trigger-http

    - name: 'node:12.10.0'
      args: ['run', 'pi']
      entrypoint: 'npm'
      id: pi
      waitFor:
          - ci
    #    - name: 'node:12.10.0'
    #      args: ['lerna', 'changed']
    #      entrypoint: 'npm'
    #      id: lerna
    #      waitFor:
    #          - ci
    - name: 'node:12.10.0'
      args: ['run', 'lint', '--', '--since']
      entrypoint: 'npm'
      id: lint
      waitFor:
          - pi
    - name: 'node:12.10.0'
      args: ['run', 'test', '--', '--since']
      entrypoint: 'npm'
      id: test
      waitFor:
          - pi
    - name: 'node:12.10.0'
      args: ['run', 'build', '--', '--since']
      entrypoint: 'npm'
      id: build
      waitFor:
          - pi
#  - name: 'node:12.10.0'
#    args: ['run', 'build', '--', '--since']
#    entrypoint: 'npm'
#    waitFor:
#      - build

substitutions:
    _NODE_VERSION: 12.10.0 #default value

