version: 2


defaults: &defaults
  working_directory: ~/tmp
  docker:
    - image: circleci/node:11

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Linter
          command: npm run lint
  build:
#    working_directory: /repo
#    docker:
#      - image: circleci/node:11
#    environment:
#      PROJECT_NAME: ${PROJECT_NAME}
#      TEST_RESULTS: /tmp/test-results
    <<: *defaults
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm i
      - run:
          name: Build
          command: npm run build
#  lint:
#    working_directory: /go/src/github.com/tufin/circleci-monorepo
#    docker:
#      - image: circleci/node:11
#    environment:
#      PROJECT_NAME: ${PROJECT_NAME}
#      TEST_RESULTS: /tmp/test-results
#    steps:
#      - checkout
#      - run:
#          name: install-npm-wee
#          command: npm install
#      - run:
#          name: Lint
#          command: npm run lint
#      - run:
#          name: Build
#          command: lerna run build --scope ${PROJECT_NAME}
#      - run:
#          name: Run Tests
#          command: lerna run test --scope ${PROJECT_NAME}
#      - run:
#          name: Lint
#          command: lerna run lint --scope ${PROJECT_NAME}
#      - store_artifacts:
#          path: /tmp/test-results
#          destination: raw-test-output
#      - store_test_results:
#          path: /tmp/test-results
#  service2:
#    working_directory: /go/src/github.com/tufin/circleci-monorepo
#    docker:
#      - image: tufin/circleci-golang
#    environment:
#      PROJECT_NAME: ${PROJECT_NAME}
#      TEST_RESULTS: /tmp/test-results
#    steps:
#      - checkout
#      - run:
#          name: Build
#          command: |
#            /scripts/go_build.sh ${PROJECT_NAME} ${PROJECT_NAME}
#      - run:
#          name: Run Tests
#          command: |
#            /scripts/go_test.sh ${TEST_RESULTS} ${PROJECT_NAME}
#      - store_artifacts:
#          path: /tmp/test-results
#          destination: raw-test-output
#      - store_test_results:
#          path: /tmp/test-results
