version: 2.1
orbs:
    codecov: codecov/codecov@1.0.4

aliases:
    - &update-npm
      run:
          name: update-npm
          command: sudo npm install -g npm@6
    - &restore_cache
      keys:
          - v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          - v1-node-{{ arch }}-{{ .Branch }}-
          - v1-node-{{ arch }}-
    - &install_sub_packages
      run:
          name: Install sub packages
          command: npm run pi

commands:
    lint:
        description: 'Run eslint with since parameter'
        parameters:
            since:
                type: string
                default: ''
        steps:
            - run: npm run lint -- --<< parameters.since >>
    handle_cache:
        description: Restoring, installing and saving cache for npm.
        steps:
            - *update-npm
            - restore_cache: *restore_cache
            - run:
                  name: install-npm-wee
                  command: npm i
            - save_cache:
                  name: Save node_modules cache
                  key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
                  paths:
                      - ./node_modules

defaults: &defaults
    working_directory: ~/tmp
    docker:
        - image: circleci/node:12

jobs:
    build:
        <<: *defaults
        steps:
            - checkout
            - handle_cache
            - *install_sub_packages
            - lint
            - run:
                  name: test
                  command: npm run test
            - run:
                  name: build
                  command: npm run build
            - codecov/upload

    since-build:
        <<: *defaults
        steps:
            - checkout
            - handle_cache
            - run:
                  name: pi since
                  command: npx lerna exec --parallel --since -- npm i
            - lint:
                  since: since
            - run:
                  name: test since
                  command: npx lerna exec --parallel --since -- npm run test -- -i
            - run:
                  name: build since
                  command: npx lerna run build --parallel --since

    publish_npm:
        <<: *defaults
        steps:
            - checkout
            - handle_cache
            - run:
                  name: build
                  command: npm run build
            - run:
                  name: Authenticate with registry
                  command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
            - run:
                  name: Publish package
                  command: npx lerna publish patch

workflows:
    version: 2
    build:
        jobs:
            - build:
                  filters:
                      branches:
                          only: master
            - since-build:
                  filters:
                      branches:
                          ignore: master
            - publish_npm:
                  filters:
                      branches:
                          only: master
#      - test
#      - deploy_to_npm:
#          <<: *only-deploy-tags
#          requires:
#            - build
